# Generated by Django 4.0 on 2022-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klients',
            name='istochnik',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='klients',
            name='status',
            field=models.CharField(max_length=300),
        ),
    ]
