# Generated by Django 4.0 on 2022-01-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('type', models.CharField(choices=[('Кр', 'Кружок'), ('Факульт', 'Факультатив'), ('Репет', 'Репетитор')], max_length=300)),
                ('teacher', models.ManyToManyField(to='teachers.Teachers')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='TeacherServise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_count', models.IntegerField(blank=True, null=True, verbose_name='Количество клиентов в группе')),
                ('time', models.IntegerField(null=True, verbose_name='Количество часов')),
                ('servise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servise', verbose_name='Сервис')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers', verbose_name='Учитель')),
            ],
        ),
    ]
