# Generated by Django 4.0 on 2022-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servise',
            name='teacher',
            field=models.ManyToManyField(related_name='servises', to='teachers.Teachers'),
        ),
    ]
