# Generated by Django 4.0 on 2022-02-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('klients', '0002_alter_klients_istochnik_alter_klients_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=100, verbose_name='Задача')),
                ('deadline', models.DateField(verbose_name='Срок выполнения')),
                ('checked', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('hr_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.user', verbose_name='Пользователь')),
                ('klient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='klients.klients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
